### ISSUE TITLE
Using account CSV -ac still checks config.ini for user/password and authtype

### ISSUE THREAD

**Issue by Darkknightz** [PokemonGoMap/PokemonGo-Map#1155]
My config contains a default password and a default auth type 

## Expected Behavior

Use only logins mentioned in the file mentioned in -ac.

## Current Behavior

Following output when specifying 71 accounts in my CSV.
 
 - The number of provided passwords (72) must match the username count (71)
 - The number of provided auth (72) must match the username count (71)

## Possible Solution

Ignore config.ini authtype/user/password when using -ac

## Steps to Reproduce (for bugs)

1. Add a password/auth type in config.ini
2. Specify an account.csv in -ac

## Context

Unable to start when using a pre-configured password/auth type in config file.
I would have to specify the passwords again in my commands.

## Your Environment

* Version used: Latest as of 5-9-2016 9:00am CEST (UTC+2)
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Debian 8

**Comment by justsomedudeonthenet** [comment]
This is not an error.  Your configuration file is wrong.  Fix your configuration.

The map combines accounts specified in config.ini, on the command line and in the CSV file.  If you are no longer specifying any on the command line or in config.ini, you shouldn't have authtype specified in them either.

**Comment by Darkknightz** [comment]
I am using a mix, one SS using -ac, and multiple commands using hex with accounts specified.

Not using an authtype gives me #1128

**Comment by PhantonQuad** [comment]
I get the same error, I had 1 password added to the config.ini as I use the config file to run multiple servers on different ports, they all have the same password so I simply added this to the config.ini. I have a -ss beehive running now using the -ac feature(great by the way!), it gave the error 'The number of provided passwords.....' same as you @Darkknightz where the password count was +1 of the username count.

To work around I added the password into the startup commands I use for the servers and removed it from the config.ini, worked great straight away.

**Comment by justsomedudeonthenet** [comment]
Resolved in https://github.com/PokemonGoMap/PokemonGo-Map/commit/d5d6d10c92103cd0535d71cb06b73c66c1de361d

**Comment by leolobato** [comment]
This is still an issue if I specify more accounts on config.ini than the csv file.

For example: I have 249 accounts specified on config.ini. If I try to run a second instance with `-ac` and a csv file which has 51 accounts, I get the following error messages:

```
 - The number of provided passwords (51) must match the username count (249)
 - The number of provided auth (51) must match the username count (249)
```
