### ISSUE TITLE
problem to run the map[win10]

### ISSUE THREAD

**Issue by malnc** [PokemonGoMap/PokemonGo-Map#172]
when i try to run the program to begin the scans i got this, what should i do to fix it
(i already tried to uninstall req and reinstall it with "--upgrade" like i saw in other topics but no changes)

 Traceback (most recent call last):
  File "runserver.py", line 29, in <module>
    import pgoapi
  File "C:\Python27\lib\site-packages\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "C:\Python27\lib\site-packages\pgoapi\auth_google.py", line 33, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb' 

## Your Environment
* Environment name and version : Python 2.7
* Operating System and version (desktop or mobile): windows 10

**Comment by Cronick** [comment]
run "pip install -r requirements.txt" and it should fix it.

**Comment by malnc** [comment]
nope, i've already tried to uninstall and then reinstall it with the upgrade but it still doesn't work and the error message is the same

**Comment by Genaga** [comment]
I'm getting the same. Even reinstalled python in 32-bit instead of 64-bit

**Comment by invisiblek** [comment]
https://pgm.readthedocs.io/en/develop/extras/faq.html

**Comment by BaIthamel** [comment]
I think this is an 8th level error.
