### ISSUE TITLE
First search step of every worker returns 0/0/0

### ISSUE THREAD

**Issue by Shobba** [PokemonGoMap/PokemonGo-Map#462]
## Expected Behavior
After successful login every worker should find something (spawn, pokestop and/or gym) during its first search step and following steps.

## Current Behavior
After successful login the first search step of every worker (even with just one account) returns 'Upserted 0 pokemon, 0 pokestops, and 0 gyms'. Starts working correctly with its seconds search step.

```
2016-08-11 00:27:51,358 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-11 00:27:51,361 [   search_thread][        search][    INFO] Search overseer starting
2016-08-11 00:27:51,363 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-11 00:27:51,367 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-11 00:27:51,370 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 1)
2016-08-11 00:27:51,372 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: xxxxxxx
2016-08-11 00:27:52,084 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-11 00:27:52,084 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-11 00:27:52,224 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-11 00:27:53,095 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 00:28:02,374 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 59)
2016-08-11 00:28:06,467 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 539 pokestops, and 17 gyms
2016-08-11 00:28:13,376 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 58)
2016-08-11 00:28:17,374 [ search_worker_0][        models][    INFO] Upserted 2 pokemon, 529 pokestops, and 18 gyms
```

Two workers:
```
2016-08-11 00:35:52,750 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-11 00:35:52,754 [   search_thread][        search][    INFO] Search overseer starting
2016-08-11 00:35:52,754 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-11 00:35:52,758 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-11 00:35:52,759 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 2)
2016-08-11 00:35:52,761 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: xxxxxxxx
2016-08-11 00:35:53,469 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-11 00:35:53,469 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-11 00:35:53,607 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-11 00:35:54,595 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 00:35:56,763 [ search_worker_1][        search][    INFO] Search step 2 beginning (queue size is 59)
2016-08-11 00:35:56,764 [ search_worker_1][      auth_ptc][    INFO] PTC User Login for: yyyyyyyy
2016-08-11 00:35:57,445 [ search_worker_1][      auth_ptc][    INFO] PTC User Login successful.
2016-08-11 00:35:57,446 [ search_worker_1][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-11 00:35:57,583 [ search_worker_1][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-11 00:35:58,296 [ search_worker_1][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-11 00:36:00,763 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 58)
2016-08-11 00:36:04,765 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 529 pokestops, and 18 gyms
2016-08-11 00:36:04,769 [ search_worker_1][        search][    INFO] Search step 4 beginning (queue size is 57)
2016-08-11 00:36:08,761 [ search_worker_0][        search][    INFO] Search step 5 beginning (queue size is 56)
2016-08-11 00:36:08,888 [ search_worker_1][        models][    INFO] Upserted 3 pokemon, 541 pokestops, and 18 gyms
2016-08-11 00:36:12,767 [ search_worker_1][        search][    INFO] Search step 6 beginning (queue size is 55)
2016-08-11 00:36:13,111 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 548 pokestops, and 17 gyms
2016-08-11 00:36:16,761 [ search_worker_0][        search][    INFO] Search step 7 beginning (queue size is 54)
2016-08-11 00:36:18,660 [ search_worker_1][        models][    INFO] Upserted 2 pokemon, 506 pokestops, and 15 gyms
2016-08-11 00:36:20,766 [ search_worker_1][        search][    INFO] Search step 8 beginning (queue size is 53)
2016-08-11 00:36:23,748 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 526 pokestops, and 16 gyms
```

## Possible Solution
Perhaps the login request counts to the request limit and it needs to pause some (10?) seconds after login before starting the first search step.
Or the first search step starts before access token is successfully received?

## Steps to Reproduce (for bugs)
Start scanning and check the log directly after login was successful

## Your Environment

* Version used: Commit 5ac7627
* Environment name and version: Python 2.7

**Comment by CoolCanuck** [comment]
Have you tried another starting location? I can't reproduce. 
![image](https://cloud.githubusercontent.com/assets/15615155/17573581/5c085db4-5f29-11e6-8c1a-dd638b7149d6.png)

**Comment by Shobba** [comment]
Just tried again in 3 different locations, same result everywhere.

**Comment by Dmurph24** [comment]
@Shobba I am having the same problem. Where is your server deployed? Is it a personal server or setup through someone else?

**Comment by Shobba** [comment]
It's running on my space at http://uberspace.de.
Just set it up on my Macbook and it's working fine there...

**Comment by pkduck09** [comment]
Your IP may got soft-banned. I had the same issue ytd and was released after 4 hours.

**Comment by Shobba** [comment]
Soft-ban just for the first search step? I'll check tomorrow again and will report if something changed!

**Comment by JZ6** [comment]
You have to login into the worker and accept the TOS, or use a tos accepting scrript

**Comment by rrbailey89** [comment]
I see the same thing. First worker 0,0,0 where it used to always pick up something on the first scan. Each subsequent scan picks up stuff though. This started today for me.

**Comment by TallGuy74** [comment]
Just another datapoint. I'm seeing the same thing.

**Comment by Slivo-fr** [comment]
Same issue there

**Comment by crckdns** [comment]
Same issue here with every account, tested on local and several remote machines located spread in country. 
It's always the first search step returning 0,0,0 
It seems, it's requesting too fast after login, not respecting the 7 seconds delay.

**Comment by Shobba** [comment]
@JZ6 Already used a script to accept the TOS, unfortunately that's not the solution.

**Comment by lota7** [comment]
Confirmed, first step always returns 0,0,0, while subsequent upserts fine.

**Comment by TallGuy74** [comment]
Upgrading to the latest commit solves things for me. I'm not sure if it's the newer version of the API included. I was running 19 commits behind HEAD at the time of this writing.

**Comment by Shobba** [comment]
Unfortunately didn't work for me. I'm on 83fab06 now

**Comment by CoolCanuck** [comment]
@Balthamel .. This is my second time asking for you to perhaps explain your reasoning before closing. It's quite rude otherwise.

**Comment by Slivo-fr** [comment]
Agree

**Comment by BaIthamel** [comment]
I thought it was a duplicate.

**Comment by rrbailey89** [comment]
@BaIthamel actually I believe that this has been fixed.

**Comment by Shobba** [comment]
Nope, I guess I've seen a fix in one of those PRs, but just checked again on the latest commit and the problem is still there.

**Comment by CoolCanuck** [comment]
Clear proof that we need to explain before closing. Time has been wasted because the issue was closed prematurely without any known reason and a huge waste of time. Unbelievable.

**Comment by pyr0ball** [comment]
Checking in to see if anyone's tested this on latest commit. Issue still present?
