### ISSUE TITLE
Documentation suggests to use root-user for MySQL

### ISSUE THREAD

**Issue by hkuiyo** [PokemonGoMap/PokemonGo-Map#659]
https://github.com/PokemonGoMap/PokemonGo-Map/wiki/How-to-start-using-a-MySQL-Server This piece of documentation suggests the use of the root-user for MySQL. We should never ever do that, technical guys will know that, but most people will just follow the guide and not create a specific user with scoped rights exactly for the PokemonGo-Map.

**Comment by Somnium42** [comment]
I will fix this and push a pullrq when im at home (at least for linux) 
The only thing i will change will be linux and how to create a new db and db-user where de user has only access to to said db.
I will be at home in 8h, if someone else is willed to do it for windows pls go ahed
Best regards

**Comment by echo465** [comment]
What rights are needed and where?  Does a login that just does canning only need INSERT?  Does a login that is only running the webserver only need SELECT?

**Comment by Cy4n1d3** [comment]
Just restrict rights to a single database.

**Comment by echo465** [comment]
That's a start, but every scanning instance doesn't need the authority to drop the database.  It looks like a scanner needs DELETE access, for some reason.  Otherwise:

`[ search_worker_0][        models][ WARNING] (1142, u"DELETE command denied to user 'xxx'@'xxx' for table 'pokemon'")... Retrying`

**Comment by angrymoose** [comment]
@echo465 it needs delete at minimum because there is a delete old pokemon sightings option.I believe its an option based on numbers of days.

**Comment by echo465** [comment]
@angrymoose Are you talking about the -pd and -cd command line options?  Those are going to be an exception, not the rule, and neither of those are default options.  It would be nice if there was some way to let "my boyfriend's sister's roomate's cousin" to run a scanner and shove data into my database without trusting them with the whole thing.  Principle of least privilege and all that.

**Comment by jnovack** [comment]
This is a stupid problem with `peewee`.  Apparently in #666 they figured out that the mysql library does a `DELETE` and an `INSERT` rather than a true `UPSERT`.

Although, the `scanned_locations`gets deleted occasionally.  And when `gym_details` gets merged (#666, again), it'll need `DELETE` as well.

**Comment by pyr0ball** [comment]
Fixed original issue. Added instructions for non-root MySQL user on commit 5eef8d6

Please seek assistance on the [Support Forum](http://pokemongo-map.me) or Discord for further configuration

**Comment by echo465** [comment]
Still doesn't fix the underlying issue.  Every scanning account shouldn't have unlimited read/write/delete/drop rights for the whole database.

**Comment by jnovack** [comment]
Project won't last long enough for people to set up permissions and have a structure.

We're on borrowed time as it is.

**Comment by EvilLost** [comment]
I believe the "workerstatus" table also uses DEL lines occasionally? (I vaguely recall seeing the error during testing). 

I agree re: unlimited access but have found no workarounds yet. 

My personal solution is to just setup a secondary DB and clone the data on a nightly basis. In case of trolls, at least I only lose 1 day's worth of data.

However, I think a built in webhook listener is needed. I have one working but have no idea how to turn that into a PR.
